[package]
name = "vocfreq-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "vocfreq"
path = "src/main.rs"

[dependencies]
vocfreq-core = { path = "../vocfreq-core" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
rayon.workspace = true
